export const HONG_KONG_SCHOOLS = [
  // Central and Western District
  "Island School",
  "Hong Kong Academy",
  "King's College",
  "Lok Sin Tong Leung Kau Kui College",
  "Sacred Heart Canossian College",
  "St. Clare's Girls' School",
  "St. Joseph's College",
  "St. Louis School",
  "St. Paul's Co-educational College",
  "St. Paul's College",
  "St. Stephen's Church College",
  "St. Stephen's Girls' College",
  "Ying Wa Girls' School",
  "Raimondi College",

  // Eastern District
  "Belilios Public School",
  "Canossa College",
  "Caritas Chai Wan Marden Foundation Secondary School",
  "Caritas Lok Yi School",
  "CCC Kwei Wah Shan College",
  "Cheung Chuk Shan College",
  "The Chinese Foundation Secondary School",
  "Chinese International School",
  "Chong Gene Hang College",
  "Clementi Secondary School",
  "CNEC Lau Wing Sang Secondary School",
  "Cognitio College (Hong Kong)",
  "Delia School of Canada",
  "Fortress Hill Methodist Secondary School",
  "Fukien Secondary School (Siu Sai Wan)",
  "Henrietta Secondary School",
  "HKCT Adult Education Centre (Shau Kei Wan Government Secondary School)",
  "Hon Wah College",
  "Hong Kong Chinese Women's Club College",
  "Hongkong Japanese School (Junior Secondary Section)",
  "Islamic Kasim Tuet Memorial College",
  "Kellett School",
  "Kiangsu-Chekiang College, North Point",
  "Lingnan Hang Yee Memorial Secondary School",
  "Lingnan Secondary School",
  "Man Kiu College",
  "Methodist Church Hong Kong Wesley College",
  "Munsang College (Hong Kong Island)",
  "Po Leung Kuk Yu Lee Mo Fan Memorial School",
  "Precious Blood Secondary School",
  "Pui Kiu Middle School",
  "Rotary Club of Hong Kong Island West Hong Chi Morninghope School",
  "Salesian English School (Secondary)",
  "Shau Kei Wan East Government Secondary School",
  "Shau Kei Wan Government Secondary School",
  "Sheng Kung Hui Li Fook Hing Secondary School",
  "St. Joan of Arc Secondary School",
  "St. Mark's School",

  // Islands District
  "Caritas Wu Cheng Chung Secondary School",
  "Buddhist Fat Ho Memorial College",
  "Buddhist Wai Yan Memorial College",
  "Caritas Chan Chun Ha Field Studies Centre",
  "Caritas Charles Vath College",
  "Cheung Chau Government Secondary School",
  "Christian Zheng Sheng College",
  "Discovery Bay International School",
  "Discovery College",
  "HKFEW Wong Cho Bau Secondary School",
  "Ho Yu College and Primary School",
  "Ling Liang Church E Wun Secondary School",
  "Po Leung Kuk Mrs. Ma Kam Ming-Cheung Fook Sien College",
  "Tung Chung Catholic School",
  "YMCA of Hong Kong Christian College",

  // Southern District
  "Aberdeen Baptist Lui Ming Choi College",
  "Aberdeen Technical School",
  "Canadian International School of Hong Kong",
  "Caritas Chong Yuet Ming Secondary School",
  "Ebenezer New Hope School",
  "Ebenezer School",
  "German Swiss International School",
  "Hong Kong International School",
  "Hong Kong Juvenile Care Centre Chan Nam Cheong Memorial School",
  "Hong Kong Red Cross John F. Kennedy Centre",
  "Hong Kong Sea School",
  "Hong Kong True Light College",
  "Hong Kong University Graduate Association College",
  "Independent Schools Foundation Academy",
  "Marycove School",
  "Po Leung Kuk Wai Yin College",
  "Pui Tak Canossian College",
  "Pui Ying Secondary School",
  "San Wui Commercial Society Chan Pak Sha School",
  "Sheng Kung Hui Lui Ming Choi Secondary School",
  "Singapore International School",
  "South Island School",
  "St. Peter's Secondary School",
  "St. Stephen's College",
  "Tung Wah Group of Hospitals Tsui Tsin Tong School",
  "Victoria Shanghai Academy",
  "West Island School",
  "Yu Chun Keung Memorial College No.2",

  // Wan Chai District
  "Anantara College (Hong Kong)",
  "Buddhist Wong Fung Ling College",
  "CCC Kung Lee College",
  "Concordia Lutheran School - North Point",
  "Confucius Hall Middle School",
  "HKCT Adult Education Centre (Hotung Secondary School)",
  "Hong Chi Lions Morninghill School",
  "Hong Kong Tang King Po College",
  "Hotung Secondary School",
  "Island School (ESF)",
  "Jockey Club Hong Chi School",
  "Lycée Français International Victor Segalen",
  "Marymount Secondary School",
  "Queen's College",
  "Queen's College Old Boys' Association Evening School",
  "Rosaryhill School (Secondary Section)",
  "Sheng Kung Hui Tang Shiu Kin Secondary School",
  "St. Francis' Canossian College",
  "St. Paul's Convent School",
  "St. Paul's Secondary School",
  "Tang Shiu Kin Victoria Government Secondary School",
  "True Light Middle School of Hong Kong",
  "Tung Wah Group of Hospitals Lee Ching Dea Memorial College",
  "Wah Yan College, Hong Kong",

  // Kowloon City District
  "American International School",
  "Amoy College",
  "Anantara College",
  "Arts and Technology Education Centre",
  "Australian International School Hong Kong",
  "Bishop Hall Jubilee School",
  "Carmel Secondary School",
  "CCC Kei To Secondary School",
  "Chan Sui Ki (La Salle) College",
  "Christian Alliance P. C. Lau Memorial International School",
  "Diocesan Boys' School",
  "Diocesan Girls' School",
  "Heep Yunn School",
  "HKICC Lee Shau Kee School of Creativity",
  "Hoi Ping Chamber of Commerce Secondary School",
  "Holy Carpenter Secondary School",
  "Holy Family Canossian College",
  "Homantin Government Secondary School",
  "Jockey Club Government Secondary School",
  "Jockey Club Sarah Roe School",
  "King George V School",
  "Kingston International School",
  "Kowloon Tong School",
  "Kowloon True Light Middle School",
  "La Salle College",
  "Mary Rose School",
  "Maryknoll Convent School (Secondary Section)",
  "Munsang College",
  "New Asia Middle School",
  "Notre Dame College",
  "Pentecostal School",
  "Po Leung Kuk Ngan Po Ling College",
  "Pooi To Middle School",
  "Pui Ching Middle School",
  "Rhenish Church Pang Hok-ko Memorial College",
  "Scientia Secondary School",
  "Sear Rogers International School – Peninsula",
  "Sheng Kung Hui Holy Trinity Church Secondary School",
  "Sheng Kung Hui Tsoi Kung Po Secondary School",
  "Shun Tak Fraternal Association Seaward Woo College",
  "St. Teresa Secondary School",
  "Tang King Po School, Kowloon",
  "Times College",
  "Tung Wah Group of Hospitals Wong Fut Nam College",
  "Wa Ying College",
  "Yew Chung International School – Secondary",
  "Yu Chun Keung Memorial College",
  "YWCA Hioe Tjo Yoeng College",

  // Kwun Tong District
  "Buddhist Ho Nam Kam College",
  "CCC Kei Chi Secondary School",
  "CCC Kei Shun Special School",
  "CCC Mong Man Wai College",
  "Delia Memorial Evening School (Kwun Tong)",
  "Delia Memorial Matriculation Evening Course (Kwun Tong)",
  "Delia Memorial School (Hip Wo)",
  "Delia Memorial School (Matteo Ricci)",
  "Delia Memorial School (Yuet Wah)",
  "Evan China Fellowship Holy Word School",
  "ECF Saint Too Canaan College",
  "FDBWA Szeto Ho Secondary School",
  "Fukien Secondary School",
  "HKWMA Chu Shek Lun Secondary School",
  "Hong Kong Red Cross Princess Alexandra School",
  "Hong Kong Sheng Kung Hui Bishop Hall Secondary School",
  "Hong Kong Taoist Association Ching Chung Secondary School",
  "Ko Lui Secondary School",
  "Kwun Tong Government Secondary School",
  "Kwun Tong Kung Lok Government Secondary School",
  "Kwun Tong Lutheran College",
  "Kwun Tong Lutheran Evening School",
  "Kwun Tong Maryknoll College",
  "Leung Shek Chee College",
  "Maryknoll Secondary School",
  "Mission Covenant Church Holm Glad College",
  "Mu Kuang English School",
  "Ning Po College",
  "Ning Po No.2 College",
  "NLSI Lui Kwok Pat Fong College",
  "Po Chiu Catholic Secondary School",
  "Sheng Kung Hui Kei Hau Secondary School",
  "Sheng Kung Hui Leung Kwai Yee Secondary School",
  "Shun Lee Catholic Secondary School",
  "Sing Yin Secondary School",
  "Society of Boys' Centres Shing Tak Centre School",
  "St. Antonius Girls' College",
  "St. Catharine's School for Girls",
  "St. Joseph's Anglo-Chinese School",
  "St. Paul's School (Lam Tin)",
  "United Christian College (Kowloon East)",
  "Yan Chai Hospital Law Chan Chor Si College",

  // Sham Shui Po District
  "Buddhist Tai Hung College",
  "Caritas Jockey Club Lok Yan School",
  "CCC Ming Yin College",
  "Chan Shu Kui Memorial School",
  "Cheung Sha Wan Catholic Secondary School",
  "Chi Yun School",
  "China Holiness College",
  "CMA Secondary School",
  "Concordia International School",
  "Concordia Lutheran Evening School",
  "Concordia Lutheran School (Hong Kong)",
  "Delia Memorial Matriculation Evening Course (Broadway)",
  "Delia Memorial Matriculation Evening Course (Glee Path)",
  "Delia Memorial School (Broadway)",
  "Delia Memorial School (Glee Path)",
  "Heung To Middle School",
  "HKCT Adult Education Centre (Kowloon Technical School)",
  "HKSYC & IA Wong Tai Shan Memorial College",
  "Holy Trinity College",
  "Kowloon Technical School",
  "Maria College",
  "Maria Evening College",
  "Maryknoll Fathers' School",
  "Mental Health Association of Hong Kong - Cornwall School",
  "Nam Wah Catholic Secondary School",
  "Our Lady of the Rosary College",
  "Po Leung Kuk Choi Kai Yau School",
  "Po Leung Kuk Vicwood K.T. Chong Sixth Form College",
  "Po Leung Kuk Tong Nai Kan Junior Secondary College",
  "Saviour Lutheran School",
  "Sheng Kung Hui St. Mary's Church Mok Hing Yiu College",
  "Society of Boys' Centres Chak Yan Centre School",
  "Society of Boys' Centres Hui Chung Sing Memorial School",
  "St. Margaret's Co-educational English Secondary and Primary School",
  "Tack Ching Girls' Secondary School",
  "Tak Nga Secondary School",
  "Tsung Tsin Christian Academy",
  "Tsung Tsin Middle School",
  "Tung Wah Group of Hospitals Chang Ming Thien College",
  "Tung Wah Group of Hospitals Kwan Fong Kai Chi School",
  "United Christian College",
  "Wai Kiu College",
  "Wai Kiu Evening College",
  "Ying Wa College",

  // Wong Tai Sin District
  "Assembly of God Evening Secondary School",
  "Assembly of God Morrison College",
  "Buddhist Hung Sean Chau Memorial College",
  "Caritas Pelletier School",
  "CCC Heep Woh College",
  "CCC Kei Heep Secondary School",
  "CCC Rotary Secondary School",
  "Chi Lin Buddhist Secondary School",
  "Choi Hung Estate Catholic Secondary School",
  "Chun Tok School",
  "Cognitio College (Kowloon)",
  "Good Hope School",
  "Ho Lap College (Sponsored by Sik Sik Yuen)",
  "Hong Kong Red Cross Margaret Trench School",
  "International Christian Quality Music Secondary and Primary School",
  "Kit Sam Lam Bing Yim Secondary School",
  "Lee Kau Yan Memorial School",
  "Lok Sin Tong Wong Chung Ming Secondary School",
  "Lok Sin Tong Yu Kan Hing Secondary School",
  "Lung Cheung Government Secondary School",
  "Ng Wah Catholic Secondary School",
  "Our Lady's College",
  "PHC Wing Kwong College",
  "Po Leung Kuk Celine Ho Yam Tong College",
  "Po Leung Kuk Centenary School",
  "Po Leung Kuk No.1 College (Evening Section)",
  "Po Leung Kuk No.1 W. H. Cheung College",
  "Rhenish Church Grace School",
  "Salvation Army William Booth Secondary School",
  "Sheng Kung Hui St. Benedict's School",
  "St. Bonaventure College and High School",
  "Stewards Pooi Tun Secondary School",
  "Tak Oi Secondary School",

  // Yau Tsim Mong District
  "CCC Ming Kei College",
  "CCC Mongkok Church Kai Oi School",
  "ELCHK Lutheran Secondary School",
  "HKCT Adult Education Centre (Queen Elizabeth School)",
  "Hong Kong and Kowloon Chiu Chow Public Association Secondary School",
  "HKMA David Li Kwok Po College",
  "Kowloon Sam Yuk Secondary School",
  "Lai Chack Middle School",
  "Lung Kong World Federation School Limited Lau Wong Fat Secondary School",
  "Methodist College",
  "Newman Catholic College",
  "PLK Vicwood KT Chong Sixth Form College",
  "Po Leung Kuk Vicwood K. T. Chong Sixth Form College (Evening School)",
  "Queen Elizabeth School",
  "Sheng Kung Hui All Saints' Middle School",
  "Sir Ellis Kadoorie Secondary School (West Kowloon)",
  "St. Francis Xavier's College, Tai Kok Tsui",
  "St. Mary's Canossian College",
  "True Light Girls' College",
  "Wah Yan College, Kowloon",

  // Kwai Tsing District
  "Buddhist Sin Tak College",
  "Buddhist Yip Kei Nam Memorial College",
  "Caritas St. Joseph Secondary School",
  "Carmel Alison Lam Foundation Secondary School",
  "CCC Chuen Yuen College",
  "CCC Yenching College",
  "CNEC Christian College",
  "CNEC Lee I Yao Memorial Secondary School",
  "Cotton Spinners Association Secondary School",
  "Daughters of Mary Help of Christians Siu Ming Catholic Secondary School",
  "HKSYC & IA Chan Nam Chong Memorial College",
  "HKSYC & IA Chan Nam Chong Memorial School",
  "Hong Chi Winifred Mary Cheung Morning School",
  "Hong Kong Taoist Association the Yuen Yuen Institute No.1 Secondary School",
  "Ju Ching Chu Secondary School (Kwai Chung)",
  "Kiangsu-Chekiang College (Kwai Chung)",
  "Kwai Chung Methodist College",
  "Lai King Catholic Secondary School",
  "Lingnan Dr. Chung Wing Kwong Memorial Secondary School",
  "Lions College",
  "Lok Sin Tong Ku Chiu Man Secondary School",
  "Lok Sin Tong Leung Chik Wai Memorial School",
  "Lutheran School for the Deaf",
  "Methodist Lee Wai Lee College",
  "Po Leung Kuk Lo Kit Sing (1983) College",
  "Po Leung Kuk Mr. & Mrs. Chan Pak Keung Tsing Yi School",
  "Pope Paul VI College",
  "Queen's College Old Boys' Association Secondary School",
  "Queen's College Old Boys' Association Tsing Yi Evening School",
  "Salesians of Don Bosco Ng Siu Mui Secondary School",
  "Sam Shui Natives Association Lau Pun Cheung School",
  "Shek Lei Catholic Secondary School",
  "Sheng Kung Hui Lam Woo Memorial Secondary School",
  "Shun Tak Fraternal Association Lee Shau Kee College",
  "Spastics Association of Hong Kong B. M. Kotewall Memorial School",
  "Tung Wah Group of Hospitals Chen Zao Men College",
  "Tung Wah Group of Hospitals Mrs. Wu York Yu Memorial College",
  "Tung Wah Group of Hospitals S. C. Gaw Memorial College",

  // North District
  "Caritas Fanling Chan Chun Ha Secondary School",
  "CCC Kei San Secondary School",
  "Christian Alliance S. W. Chan Memorial College",
  "De La Salle Secondary School, N.T.",
  "Elegantia College (Sponsored by Education Convergence)",
  "Fanling Government Secondary School",
  "Fanling Kau Yan College",
  "Fanling Lutheran Secondary School",
  "Fanling Rhenish Church Secondary School",
  "Fung Kai Liu Man Shek Tong Secondary School",
  "Fung Kai No.1 Secondary School",
  "HHCKLA Buddhist Ma Kam Chan Memorial English Secondary School",
  "HHCKLA Buddhist Po Kwong School",
  "Hong Kong Taoist Association Tang Hin Memorial Secondary School",
  "International College Hong Kong",
  "Po Leung Kuk Ma Kam Ming College",
  "Salvation Army Shek Wu School",
  "Sheng Kung Hui Chan Young Secondary School",
  "Sheung Shui Government Secondary School",
  "St. Francis of Assisi's College",
  "Tin Ka Ping Secondary School",
  "Tung Wah Group of Hospitals Kap Yan Directors' College",
  "Tung Wah Group of Hospitals Li Ka Shing College",

  // Sai Kung District
  "Carmel Divine Grace Foundation Secondary School",
  "Catholic Ming Yuen Secondary School",
  "Cheng Chek Chee Secondary School of Sai Kung and Hang Hau District, N.T.",
  "Christian and Missionary Alliance Sun Kei Secondary School",
  "Creative Secondary School",
  "Evangel College",
  "G. T. (Ellen Yeung) College",
  "Haven of Hope Sunnyside School",
  "Heung To Secondary School (Tseung Kwan O)",
  "HHCKLA Buddhist Ching Kok Secondary School",
  "Hong Kong Chinese Christian Churches Union Logos Academy",
  "Hong Chi Morninghill School, Tsui Lam",
  "Hong Kong Adventist Academy",
  "Hong Kong and Macau Lutheran Church Queen Maud Secondary School",
  "Hong Kong Taoist Association the Yuen Yuen Institute No.3 Secondary School",
  "King Ling College",
  "MKMCF Ma Chan Duen Hey Memorial College",
  "MKMCF Ma Chan Duen Hey Memorial Evening College",
  "Po Kok Secondary School",
  "Po Leung Kuk Ho Yuk Ching (1984) College",
  "Po Leung Kuk Laws Foundation College",
  "Pok Oi Hospital 80th Anniversary Tang Ying Hei College",
  "Man Kwan QualiEd College",
  "Sai Kung Sung Tsun Catholic School",
  "Shun Tak Fraternal Association Cheng Yu Tung Secondary School",
  "Tseung Kwan O Government Secondary School",
  "Tseung Kwan O Pui Chi School",
  "Tung Wah Group of Hospitals Lui Yun Choy Memorial College",
  "Wellington Education Organization Chang Pui Chung Memorial School",
  "Yan Chai Hospital Lan Chi Pat Memorial Secondary School",
  "Yan Chai Hospital Wong Wha San Secondary School",

  // Sha Tin District
  "Renaissance College",
  "Baptist Lui Ming Choi Secondary School",
  "Buddhist Kok Kwong Secondary School",
  "Buddhist Wong Wan Tin College",
  "Caritas Lok Jun School",
  "Caritas Ma On Shan Secondary School",
  "Caritas Resurrection School",
  "Chinese YMCA College",
  "Chiu Chow Association Secondary School",
  "Choi Jun School",
  "Christ College",
  "Christian Alliance Cheng Wing Gee College",
  "CUHKFAA Chan Chun Ha Secondary School",
  "GCC & ITKD Lau Pak Lok Secondary School",
  "Helen Liang Memorial Secondary School (Shatin)",
  "HKBUAS Wong Kam Fai Secondary and Primary School",
  "HKCT Adult Education Centre (Sha Tin Government Secondary School)",
  "Hong Kong and Kowloon CCPA Ma Chung Sum Secondary School",
  "Hong Kong Chinese Women's Club Fung Yiu King Memorial Secondary School",
  "Immaculate Heart of Mary College",
  "International Christian School",
  "Jockey Club Ti-I College",
  "Kiangsu-Chekiang College (Shatin)",
  "Kwok Tak Seng Catholic Secondary School",
  "Lam Tai Fai College",
  "Li Po Chun United World College of Hong Kong",
  "Lock Tao Secondary School",
  "Lok Sin Tong Young Ko Hsiao Lin Secondary School",
  "Ma On Shan St. Joseph's Secondary School",
  "Ma On Shan Tsung Tsin Secondary School",
  "Ng Yuk Secondary School",
  "Pentecostal Lam Hon Kwong School",
  "Po Leung Kuk C. W. Chu College",
  "Po Leung Kuk C. W. Chu Education Services Centre (Evening Section)",
  "Po Leung Kuk Wu Chung College",
  "Pok Oi Hospital Chan Kai Memorial College",
  "Pui Kiu College",
  "Sha Tin Government Secondary School",
  "Sha Tin Methodist College",
  "Shatin College",
  "Shatin Lutheran Evening School",
  "Shatin Public School",
  "Shatin Pui Ying College",
  "Shatin Tsung Tsin Secondary School",
  "Sheng Kung Hui Lam Kau Mow Secondary School",
  "Sheng Kung Hui Tsang Shiu Tim Secondary School",
  "Spastics Association of Hong Kong Ko Fook Iu Memorial School",
  "St. Rose of Lima's College",
  "Stewards Pooi Kei College",
  "Tak Sun Secondary School",
  "Toi Shan Association College",
  "Tsang Pik Shan Secondary School",
  "Tung Wah Group of Hospitals Mrs. Fung Wong Fung Ting College",
  "Tung Wah Group of Hospitals Wong Fung Ling College",
  "Tung Wah Group of Hospitals Yow Kam Yuen College",
  "Yan Chai Hospital Tung Chi Ying Memorial Secondary School",

  // Tai Po District
  "Assembly of God Hebron Evening School",
  "Assembly of God Hebron Secondary School",
  "Buddhist Tai Kwong Chi Hong College",
  "Carmel Holy Word Secondary School",
  "Carmel Pak U Secondary School",
  "CCC Fung Leung Kit Memorial Secondary School",
  "China Holiness Church Living Spirit College",
  "Confucian Ho Kwok Pui Chun College",
  "HKCT Adult Education Centre (NTHYK Tai Po District Secondary School)",
  "Hong Chi Pinehill School",
  "Hong Chi Pinehill No.2 School",
  "Hong Chi Pinehill No.3 School",
  "Hong Kong and Kowloon Kaifong Women's Association Sun Fong Chung College",
  "Hong Kong Red Swastika Society Tai Po Secondary School",
  "Hong Kong Taoist Association The Yuen Yuen Institute No.2 Secondary School",
  "Hong Kong Teachers' Association Evening Secondary School",
  "Hong Kong Teachers' Association Lee Heng Kwei Secondary School",
  "Kau Yan College",
  "Law Ting Pong Secondary School",
  "Ling Liang Church M. H. Lau Secondary School",
  "New Territories Heung Yee Kuk Tai Po District Secondary School",
  "SALEM-Immanuel Lutheran College",
  "Sheng Kung Hui Bishop Mok Sau Tseng Secondary School",
  "Spastics Association of Hong Kong Jockey Club Elaine Field School",
  "Tai Po Sam Yuk Secondary School",
  "Valtorta College",
  "Wong Shiu Chi Secondary School",

  // Tsuen Wan District
  "AD & FD POHL Leung Sing Tak College",
  "HKCT Adult Education Centre (Tsuen Wan Government Secondary School)",
  "Ho Fung College (Sponsored by Sik Sik Yuen)",
  "Ho Koon Nature Education cum Astronomical Centre",
  "Holy Cross Lutheran Evening College",
  "Liu Po Shan Memorial College",
  "Lui Ming Choi Lutheran College",
  "Po Leung Kuk Lee Shing Pik College",
  "Po Leung Kuk Yao Ling Sun College",
  "Po on Commercial Association Wong Siu Ching Secondary School",
  "Sheng Kung Hui Li Ping Secondary School",
  "St. Francis Xavier's School, Tsuen Wan",
  "Textile Institute American Chamber of Commerce Woo Hon Fai Secondary School",
  "Tsuen Wan Government Secondary School",
  "Tsuen Wan Public Ho Chuen Yiu Memorial College",
  "Yan Chai Hospital Lim Por Yen Secondary School",

  // Tuen Mun District
  "Baptist Wing Lung Secondary School",
  "Buddhist Sum Heung Lam Memorial College",
  "Caritas Tuen Mun Marden Foundation Secondary School",
  "Carmel Bunnan Tong Memorial Secondary School",
  "CCC Hoh Fuk Tong College",
  "CCC Tam Lee Lai Fun Memorial Secondary School",
  "Ching Chung Hau Po Woon Secondary School",
  "Christian Alliance College",
  "Christian Alliance S. C. Chan Memorial College",
  "Chung Sing Benevolent Society Mrs. Aw Boon Haw Secondary School",
  "CMA Choi Cheung Kok Secondary School",
  "Harrow International School Hong Kong",
  "HHCKLA Buddhist Leung Chik Wai College",
  "HKCT Adult Education Centre (Tuen Mun Government Secondary School)",
  "Ho Ngai College (Sponsored by Sik Sik Yuen)",
  "Hong Chi Morninghill School, Tuen Mun",
  "Hong Chi Morninghope School, Tuen Mun",
  "Hong Chi Morninglight School, Tuen Mun",
  "Hong Kong Christian Service Pui Oi School",
  "Ju Ching Chu Secondary School (Tuen Mun)",
  "Lui Cheung Kwong Lutheran College",
  "Lui Cheung Kwong Lutheran Evening College",
  "Madam Lau Kam Lung Secondary School of Miu Fat Buddhist Monastery",
  "NLSI Peace Evangelical Secondary School",
  "PAOC Ka Chi Secondary School",
  "Po Leung Kuk Centenary Li Shiu Chung Memorial College",
  "Po Leung Kuk Tang Yuk Tien College",
  "San Wui Commercial Society Secondary School",
  "Semple Memorial Secondary School",
  "Sheng Kung Hui St. Simon's Lui Ming Choi Secondary School",
  "Shi Hui Wen Secondary School",
  "Shun Tak Fraternal Association Leung Kau Kui College",
  "Shun Tak Fraternal Association Tam Pak Yu College",
  "South Tuen Mun Government Secondary School",
  "Stewards MKMCF Ma Ko Pan Memorial College",
  "Tsung Tsin College",
  "Tuen Mun Catholic Secondary School",
  "Tuen Mun Government Secondary School",
  "Tung Wah Group of Hospitals Mr. and Mrs. Kwong Sik Kwan College",
  "Tung Wah Group of Hospitals Sun Hoi Directors' College",
  "Tung Wah Group of Hospitals Yau Tze Tin Memorial College",
  "Yan Chai Hospital No.2 Secondary School",
  "Yan Oi Tong Chan Wong Suk Fong Memorial Secondary School",
  "Yan Oi Tong Tin Ka Ping Secondary School",
  "YPI & CA Lee Lim Ming College",

  // Yuen Long District
  "Bethel High School",
  "Buddhist Mau Fung Memorial College",
  "Buddhist TCFS Yeung Yat Lam Memorial School",
  "Caritas Lok Kan School",
  "Caritas Yuen Long Chan Chun Ha Secondary School",
  "CCC Fong Yun Wah Secondary School",
  "CCC Kei Long College",
  "CCC Kei Yuen College",
  "Chinese YMCA Secondary School",
  "Chiu Lut Sau Memorial Secondary School",
  "CUHKFAA Thomas Cheung Secondary School",
  "Cumberland Presbyterian Church Yao Dao Secondary School",
  "ELCHK Lutheran Academy",
  "ELCHK Yuen Long Lutheran College",
  "ELCHK Yuen Long Lutheran Secondary School",
  "Gertrude Simon Lutheran College",
  "Gertrude Simon Lutheran Evening College",
  "Heung To Middle School (Tin Shui Wai)",
  "Ho Dao College (Sponsored by Sik Sik Yuen)",
  "Hong Chi Morningjoy School, Yuen Long",
  "Hong Chi Morninglight School, Yuen Long",
  "Hong Kong Federation of Youth Groups Lee Shau Kee College",
  "Hong Kong Management Association K. S. Lo College",
  "Jockey Club Eduyoung College",
  "Ju Ching Chu Secondary School (Yuen Long)",
  "New Territories Heung Yee Kuk Yuen Long District Secondary School",
  "Pak Kau College",
  "Po Leung Kuk Laws Foundation School",
  "Pok Oi Hospital Tang Pui King Memorial College",
  "Pui Shing Catholic Secondary School",
  "Queen Elizabeth School Old Students' Association Secondary School",
  "Queen Elizabeth School Old Students' Association Tong Kwok Wah Secondary School",
  "Shap Pat Heung Rural Committee Kung Yik She Secondary School",
  "Sheng Kung Hui Bishop Baker Secondary School",
  "Shun Tak Fraternal Association Yung Yau College",
  "Shung Tak Catholic English College",
  "Tin Shui Wai Government Secondary School",
  "Tin Shui Wai Methodist College",
  "Tung Wah Group of Hospitals C. Y. Ma Memorial College",
  "Tung Wah Group of Hospitals Kwok Yat Wai College",
  "Tung Wah Group of Hospitals Lo Kon Ting Memorial College",
  "YLPMSAA Tang Siu Tong Secondary School",
  "Yuen Long Catholic Secondary School",
  "Yuen Long Lutheran Evening School of the ELCHK",
  "Yuen Long Merchants Association Secondary School",
  "Yuen Long Public Secondary School",
  "Yuen Yuen Institute MFBM Nei Ming Chan Lui Chung Tak Memorial College",

  // Others
  "Hong Kong Red Cross Hospital Schools"
];